# CUDA NDT Matcher - Build System

# Cargo config generated by colcon-cargo-ros2
cargo_config := "build/ros2_cargo_config.toml"
manifest := "Cargo.toml"

# Paths for testing
local_setup := "install/setup.bash"
sample_map_dir := "data/sample-map"
sample_rosbag := "data/sample-rosbag-fixed"
rosbag_output_dir := "rosbag"
ground_truth_dir := "tests/fixtures/ground_truth"

# Show available recipes
default:
    @just --list

# Check prerequisites and install build dependencies
setup:
    #!/usr/bin/env bash
    set -e
    echo "Checking prerequisites..."
    MISSING=""

    # Check Rust toolchain
    if ! command -v rustc &> /dev/null; then
        echo "  ERROR: Rust toolchain not found"
        echo "         Install via: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
        MISSING="$MISSING rust"
    else
        echo "  Rust: $(rustc --version)"
    fi

    # Check Rust nightly (for rustfmt)
    if ! rustup run nightly rustc --version &> /dev/null; then
        echo "  WARN: Rust nightly not found (needed for 'just lint')"
        echo "        Install via: rustup toolchain install nightly"
    else
        echo "  Rust nightly: $(rustup run nightly rustc --version 2>/dev/null | head -1)"
    fi

    # Check CUDA toolkit
    if ! command -v nvcc &> /dev/null; then
        echo "  ERROR: CUDA toolkit not found (nvcc)"
        echo "         Install NVIDIA CUDA Toolkit"
        MISSING="$MISSING cuda"
    else
        echo "  CUDA: $(nvcc --version | grep release | sed 's/.*release //' | sed 's/,.*//')"
    fi

    # Check ROS Humble
    if [[ ! -f /opt/ros/humble/setup.bash ]]; then
        echo "  ERROR: ROS Humble not found at /opt/ros/humble"
        MISSING="$MISSING ros-humble"
    else
        echo "  ROS Humble: /opt/ros/humble"
    fi

    # Check Autoware 1.5.0
    if [[ ! -f /opt/autoware/1.5.0/setup.bash ]]; then
        echo "  ERROR: Autoware 1.5.0 not found at /opt/autoware/1.5.0"
        MISSING="$MISSING autoware"
    else
        echo "  Autoware 1.5.0: /opt/autoware/1.5.0"
    fi

    # Check GNU Parallel (used by run_demo.sh)
    if ! command -v parallel &> /dev/null; then
        echo "  ERROR: GNU Parallel not found"
        echo "         Install via: sudo apt install parallel"
        MISSING="$MISSING parallel"
    else
        echo "  GNU Parallel: $(parallel --version | head -1)"
    fi

    # Check direnv (optional but recommended)
    if ! command -v direnv &> /dev/null; then
        echo "  WARN: direnv not found (optional, recommended for environment setup)"
        echo "        Install via: sudo apt install direnv"
    else
        echo "  direnv: $(direnv --version)"
    fi

    # Exit if required dependencies are missing
    if [[ -n "$MISSING" ]]; then
        echo ""
        echo "ERROR: Missing required dependencies:$MISSING"
        exit 1
    fi

    # Install Python dependencies
    echo ""
    echo "Installing Python build dependencies..."
    pip install -U colcon-cargo-ros2

    echo ""
    echo "Setup complete!"

# Build all packages with colcon (only check src/ directory)
build:
    #!/usr/bin/env bash
    colcon build \
        --base-paths src \
        --symlink-install \
        --cmake-args -DCMAKE_BUILD_TYPE=Release \
        --cargo-args --release

# Clean all build artifacts
clean:
    rm -rf build install log target

# Format code with rustfmt
format:
    cargo +nightly fmt --manifest-path {{manifest}} --all

# Check formatting and run clippy on all crates
lint:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo +nightly fmt --check --manifest-path {{manifest}} --all
    cargo clippy --manifest-path {{manifest}} --config {{cargo_config}} --all-targets

# Lint ndt_cuda crate only
lint-ndt-cuda:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo +nightly fmt --check --manifest-path {{manifest}} -p ndt_cuda
    cargo clippy --manifest-path {{manifest}} --config {{cargo_config}} -p ndt_cuda

# Lint cuda_ffi crate only
lint-cuda-ffi:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo +nightly fmt --check --manifest-path {{manifest}} -p cuda_ffi
    cargo clippy --manifest-path {{manifest}} --config {{cargo_config}} -p cuda_ffi

# Lint cuda_ndt_matcher crate only
lint-cuda-ndt-matcher:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo +nightly fmt --check --manifest-path {{manifest}} -p cuda_ndt_matcher
    cargo clippy --manifest-path {{manifest}} --config {{cargo_config}} -p cuda_ndt_matcher

# Run all Rust unit tests
test-rust:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo test \
        --manifest-path {{manifest}} \
        --config {{cargo_config}} \
        --all-targets

# Test ndt_cuda crate only
test-ndt-cuda:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo test \
        --manifest-path {{manifest}} \
        --config {{cargo_config}} \
        -p ndt_cuda

# Test cuda_ffi crate only
test-cuda-ffi:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo test --manifest-path {{manifest}} --config {{cargo_config}} -p cuda_ffi

# Test cuda_ndt_matcher crate only
test-cuda-ndt-matcher:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo test --manifest-path {{manifest}} --config {{cargo_config}} -p cuda_ndt_matcher

# Run Rust unit tests only (fast)
test: test-rust

# Run all tests including integration tests (slow, requires sample data)
test-all: test-rust test-integration

# Run Python integration tests (prepares data if needed)
test-integration: ensure-test-data
    #!/usr/bin/env bash
    set -eo pipefail
    cd "$(dirname {{manifest}})"

    # Check if pytest is available
    if ! command -v pytest &> /dev/null; then
        echo "pytest not found. Install with: pip install -r tests/requirements.txt"
        exit 1
    fi

    # Run integration tests
    pytest tests/test_cuda_ndt.py -v

# Ensure test data is available (idempotent)
ensure-test-data: ensure-sample-data ensure-ground-truth

# Download sample data if not present (idempotent)
ensure-sample-data:
    #!/usr/bin/env bash
    set -eo pipefail
    if [[ -d "{{sample_map_dir}}" && -d "{{sample_rosbag}}" ]]; then
        echo "Sample data already exists, skipping download"
    else
        echo "Downloading sample data..."
        ./scripts/download_sample_data.sh
    fi

# Collect ground truth if not present (idempotent)
ensure-ground-truth: ensure-sample-data
    #!/usr/bin/env bash
    set -eo pipefail
    if [[ -d "{{ground_truth_dir}}/rosbag" ]]; then
        echo "Ground truth already exists, skipping collection"
    else
        echo "Collecting ground truth data..."
        ./scripts/collect_ground_truth.sh
    fi

# Force re-collection of ground truth
refresh-ground-truth: ensure-sample-data
    #!/usr/bin/env bash
    set -eo pipefail
    echo "Refreshing ground truth data..."
    rm -rf \
        "{{ground_truth_dir}}/rosbag" \
        "{{ground_truth_dir}}/debug.jsonl" \
        "{{ground_truth_dir}}/metadata.json"
    ./scripts/collect_ground_truth.sh

# Run all quality checks (lint + test)
quality: lint test

# Download sample map and rosbag data
download-data:
    ./scripts/download_sample_data.sh

play-rosbag:
    #!/usr/bin/env bash
    set -eo pipefail
    ros2 bag play -l $(realpath {{sample_rosbag}})

# Start Autoware builtin NDT demo (delegates to tests/comparison)
run-builtin:
    cd tests/comparison && just run

# Start CUDA NDT demo (simulation + rosbag + recording)
run-cuda:
    ./scripts/run_demo.sh --cuda \
        "$(realpath {{sample_map_dir}})" \
        "$(realpath {{sample_rosbag}})" \
        "{{rosbag_output_dir}}"

# Enable NDT matching via service call
enable-ndt:
    #!/usr/bin/env bash
    ros2 service call \
        /localization/pose_estimator/trigger_node_srv \
        std_srvs/srv/SetBool \
        "{data: true}"

# Monitor NDT pose output
monitor-ndt:
    #!/usr/bin/env bash
    ros2 topic echo /localization/pose_estimator/pose_with_covariance

# === Profiling ===

# Profile all NDT modes (builtin, cuda-cpu, cuda-gpu)
profile-all:
    ./scripts/profile_ndt.sh --modes builtin,cuda-cpu,cuda-gpu

# Profile GPU modes only (faster)
profile-gpu:
    ./scripts/profile_ndt.sh --modes builtin,cuda-gpu

# Profile with perf CPU sampling (requires sudo)
profile-perf:
    ./scripts/profile_ndt.sh --modes builtin,cuda-gpu --perf

# Profile with nsys GPU profiling
profile-nsys:
    ./scripts/profile_ndt.sh --modes cuda-gpu --nsys

# Analyze existing profile results
analyze-profile dir:
    python3 ./scripts/analyze_profile.py {{dir}}

# Run CUDA NDT in CPU mode (for comparison)
run-cuda-cpu:
    NDT_USE_GPU=0 \
        ./scripts/run_demo.sh --cuda \
        "$(realpath {{sample_map_dir}})" \
        "$(realpath {{sample_rosbag}})" \
        "{{rosbag_output_dir}}"

# === Comparison Testing ===

# Build patched Autoware for comparison (required for debug output)
build-comparison:
    cd tests/comparison && just build

# Clean comparison build artifacts
clean-comparison:
    cd tests/comparison && just clean

# === Debug Data Collection ===

# Log output directory
logs_dir := "logs"

# --- Build Recipes (Selective Debug Features) ---

# Build CUDA with all debug features enabled
build-cuda-debug:
    #!/usr/bin/env bash
    colcon build \
        --base-paths src \
        --symlink-install \
        --cmake-args -DCMAKE_BUILD_TYPE=Release \
        --cargo-args --release --features debug

# Build CUDA with per-iteration debug only (JSONL output)
build-cuda-debug-iterations:
    #!/usr/bin/env bash
    colcon build \
        --base-paths src \
        --symlink-install \
        --cmake-args -DCMAKE_BUILD_TYPE=Release \
        --cargo-args --release --features debug-output

# Build CUDA with voxel dump only
build-cuda-debug-voxels:
    #!/usr/bin/env bash
    colcon build \
        --base-paths src \
        --symlink-install \
        --cmake-args -DCMAKE_BUILD_TYPE=Release \
        --cargo-args --release --features debug-voxels

# Build CUDA with voxel-per-point tracking only (ndt_cuda feature)
build-cuda-debug-vpp:
    #!/usr/bin/env bash
    colcon build \
        --base-paths src \
        --symlink-install \
        --cmake-args -DCMAKE_BUILD_TYPE=Release \
        --cargo-args --release -p ndt_cuda --features debug-vpp

# Build CUDA with GPU vs CPU covariance comparison only (ndt_cuda feature)
build-cuda-debug-cov:
    #!/usr/bin/env bash
    colcon build \
        --base-paths src \
        --symlink-install \
        --cmake-args -DCMAKE_BUILD_TYPE=Release \
        --cargo-args --release -p ndt_cuda --features debug-cov

# Build CUDA with profiling (timing + JSONL output, minimal overhead)
# Uses debug-output for JSONL but without full debug-iteration data collection
build-cuda-profiling:
    #!/usr/bin/env bash
    colcon build \
        --base-paths src \
        --symlink-install \
        --cmake-args -DCMAKE_BUILD_TYPE=Release \
        --cargo-args --release --features profiling,debug-output

# --- Run Recipes (Selective Debug Features) ---

# Run CUDA with all debug output (per-iteration data, profiling timing, voxel dump)
run-cuda-debug: build-cuda-debug
    mkdir -p {{logs_dir}}
    NDT_DEBUG_FILE={{logs_dir}}/ndt_cuda_debug.jsonl \
    NDT_DUMP_VOXELS_FILE={{logs_dir}}/ndt_cuda_voxels.json \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

# Run CUDA with per-iteration debug only (JSONL output)
run-cuda-debug-iterations: build-cuda-debug-iterations
    mkdir -p {{logs_dir}}
    NDT_DEBUG_FILE={{logs_dir}}/ndt_cuda_debug.jsonl \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

# Run CUDA with voxel dump only
run-cuda-debug-voxels: build-cuda-debug-voxels
    mkdir -p {{logs_dir}}
    NDT_DUMP_VOXELS_FILE={{logs_dir}}/ndt_cuda_voxels.json \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

# Run CUDA with profiling only (minimal overhead timing data)
run-cuda-profiling: build-cuda-profiling
    mkdir -p {{logs_dir}}
    NDT_DEBUG_FILE={{logs_dir}}/ndt_cuda_profiling.jsonl \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

# Run Autoware with profiling (timing data for comparison)
run-builtin-profiling:
    mkdir -p {{logs_dir}}
    cd tests/comparison && just run-profiling

# Compare CUDA and Autoware profiling results
compare-profiling:
    python3 tmp/profile_comparison.py

# Full profiling comparison: build, run both, compare
profile-compare: build-cuda-profiling
    #!/usr/bin/env bash
    set -e
    echo "=== Building CUDA with profiling ==="
    # Already built by dependency

    echo ""
    echo "=== Running CUDA profiling ==="
    mkdir -p {{logs_dir}}
    NDT_DEBUG_FILE={{logs_dir}}/ndt_cuda_profiling.jsonl \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

    echo ""
    echo "=== Running Autoware profiling ==="
    cd tests/comparison && just run-profiling

    echo ""
    echo "=== Comparing results ==="
    python3 tmp/profile_comparison.py

# Run Autoware with per-iteration debug output (requires build-comparison first)
run-builtin-debug:
    cd tests/comparison && just run-debug

# Dump voxel grid data for comparison (CUDA)
dump-voxels-cuda: build-cuda-debug-voxels
    mkdir -p {{logs_dir}}
    NDT_DUMP_VOXELS_FILE={{logs_dir}}/ndt_cuda_voxels.json \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

# Dump voxel grid data for comparison (Autoware, requires build-comparison first)
dump-voxels-autoware:
    cd tests/comparison && just dump-voxels

# Compare voxel grids between CUDA and Autoware
compare-voxels:
    python3 tmp/compare_voxels.py \
        {{logs_dir}}/ndt_cuda_voxels.json \
        {{logs_dir}}/ndt_autoware_voxels.json

# === Debug Analysis ===

# Analyze CUDA debug output
analyze-debug-cuda:
    python3 tmp/analyze_debug.py {{logs_dir}}/ndt_cuda_debug.jsonl

# Analyze Autoware debug output
analyze-debug-autoware:
    cd tests/comparison && just analyze-debug

# Analyze Autoware per-iteration debug output
analyze-iterations-autoware:
    cd tests/comparison && just analyze-iterations

# Analyze debug output from a specific file
analyze-debug file:
    python3 tmp/analyze_debug.py {{file}}
